### ISSUE TITLE
v1.0.2 was not published on packagist

### ISSUE THREAD

**Issue by ankurk91** [Jubeki/laravel-code-style#7]
Hi,

Look like there is some issue in packagist integration with this repo.
You tagged 1.0.2 but it is not showing on packagist.

https://github.com/Jubeki/laravel-code-style/releases/tag/1.0.2

https://packagist.org/packages/jubeki/laravel-code-style

Can you please check if this GitHub app has access to repo
https://github.com/settings/connections/applications/a059f127e1c09c04aa5a

**Comment by Jubeki** [comment]
So I checked the app and configured webhooks.

It seems the webhook could not be delivered because of `could not connect to host` a manual update on packagist and redelivering the webhook worked both.

Seems to be a one time problem, which should normally not occur.

Thanks for reporting!
